services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    stdin_open: true 
    tty: true
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: pillowdb3
    ports:
      - "27017:27017"
    volumes:
      - ./data1:/data/db
  nats-server:
    image: nats
    container_name: nats-server
    ports:
      - "4222:4222"
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=root123456
      - DOCKER_INFLUXDB_INIT_ORG=mina.org
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
  # sensor:
  #   image: sensor
  #   container_name: sensor
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongodb

  