services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - BRIDGE
    stdin_open: true 
    tty: true
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: pillowdb3
    ports:
      - "27017:27017"
    volumes:
      - ./data1:/data/db
    networks:
      - BRIDGE
  nats-server:
    image: nats
    container_name: nats-server
    ports:
      - "4222:4222"
    networks:
      - BRIDGE
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=root123456
      - DOCKER_INFLUXDB_INIT_ORG=mina.org
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    networks:
      - BRIDGE
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning:/etc/grafana/provisioning/
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_ORG=mina.org
      - INFLUXDB_BUCKET=sensor_data
      - GF_INFLUXDB_TOKEN=mytoken
      - GF_LOG_LEVEL=debug
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - BRIDGE
  emanager:
    image: emqx/ekuiper-manager:1.8
    container_name: emanager
    ports:
      - "9082:9082"
    restart: unless-stopped	
    environment:
      - DEFAULT_EKUIPER_ENDPOINT=http://ekupier:9081
    networks:
      - BRIDGE
  ekupier:
    image: lfedge/ekuiper:latest
    ports:
      - "9081:9081"
      - "127.0.0.1:20498:20498"
    container_name: ekupier
    hostname: ekupier
    restart: unless-stopped
    user: root
    volumes:
      - ./eKuiper/data/init.json:/kuiper/data/init.json:ro
      # - /tmp/data:/kuiper/data
      # - /tmp/log:/kuiper/log
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://mosquitto:1883"
      KUPIER__BASIC__CONSOLELOG: "true"
      KUPIER__BASIC__IGNORECASE: "false"
    depends_on:
      - mosquitto
    networks:
      - BRIDGE
  sensor:
    image: sensor
    container_name: sensor
    ports:
      - "3001:3001"
    networks:
      - BRIDGE
    depends_on:
      - mongodb
  filter:
    image: filter
    container_name: filter
    networks:
      - BRIDGE
    depends_on:
      - mosquitto
      - nats-server
  dashboard:
    image: dashboard
    container_name: dashboard
    networks:
      - BRIDGE
    depends_on:
      - influxdb
      - filter

  # command_server:
  #   image: command_image
  #   container_name: command_server
  #   ports:
  #     - "8888:8080"
  #   networks:
  #     - BRIDGE
  # web_page:
  #   image: nginx:latest
  #   container_name: web_page
  #   volumes:
  #     - ./Command/mqtttosocket/index.html:/usr/share/nginx/html/index.html
  #   ports:
  #     - "80:80"
  #   networks:
  #     - BRIDGE
networks:
  BRIDGE:
    driver: bridge
    
  
  