# Dockerfile

# Use official Node.js image with a specific version as base image
FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY . .

# Expose MQTT and WebSocket ports
EXPOSE 1883 8080

# Command to run the Node.js application
CMD [ "node", "mqtt_subscriber.js" ]
